### ISSUE TITLE
difference with https://github.com/kubernauts/jmeter-kubernetes?

### ISSUE THREAD

**Issue by LeiYangGH** [kaarolch/kubernetes-jmeter#4]
This is not a issue but I don't know where else to ask.

**Comment by kaarolch** [comment]
@LeiYangGH different approach. I use the helmchart, currently no plan to implement operator and special support for openshift custom things. In next few week I would plan to bump version of tools and add a few other feature.
Basically I created this repo because I could not find jmeter helm package.

**Comment by LeiYangGH** [comment]
thanks. i'm just a QA of some cloud products and looking for some existing framework of jmeter in k8s. i looked both of the 2 repos but still not know which to choose yet(^_^)
please feel free to close this issue.
